<a href="https://colab.research.google.com/github/haimran81/datasci_1_loading/blob/main/datasci_1_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import json

In [3]:
iris_df = pd.read_csv("data/iris.csv")

In [4]:
iris_df.head(10)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

####Iris Features
- **Sepal.Length** – The length of the iris flower's sepal, measured in centimeters.
- **Sepal.Width** – The width of the iris flower's sepal, measured in centimeters.
- **Petal.Length** – The length of the iris flower's petal, measured in centimeters.
- **Petal.Width** – The width of the iris flower's petal, measured in centimeters.
- **Species** – The species or type of iris flower. The dataset contains setosa, versicolor, and virginica.

In [5]:
air_df = pd.read_csv("data/AirPassengers.csv")

air_df.head(10)

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121
5  1949-06          135
6  1949-07          148
7  1949-08          148
8  1949-09          136
9  1949-10          119

### Air Passengers Dataset Features

- **Month:** Month and year of the observation.
- **Passengers:** Number of airline passengers recorded during that month.

In [6]:
cardio_df = pd.read_csv("data/Cardiotocographic.csv")

cardio_df.head(10)

,LB,AC,FM,UC,DL,DS,DP,ASTV,MSTV,ALTV,...,Min,Max,Nmax,Nzeros,Mode,Mean,Median,Variance,Tendency,NSP
0,120,0.000000,0.0,0.000000,0.000000,0.0,0.000000,73,0.5,43,...,62,126,2,0,120,137,121,73,1,2
1,132,0.006380,0.0,0.006380,0.003190,0.0,0.000000,17,2.1,0,...,68,198,6,1,141,136,140,12,0,1
2,133,0.003322,0.0,0.008306,0.003322,0.0,0.000000,16,2.1,0,...,68,198,5,1,141,135,138,13,0,1
3,134,0.002561,0.0,0.007682,0.002561,0.0,0.000000,16,2.4,0,...,53,170,11,0,137,134,137,13,1,1
4,132,0.006515,0.0,0.008143,0.000000,0.0,0.000000,16,2.4,0,...,53,170,9,0,137,136,138,11,1,1
5,134,0.001049,0.0,0.010493,0.009444,0.0,0.002099,26,5.9,0,...,50,200,5,3,76,107,107,170,0,3
6,134,0.001403,0.0,0.012623,0.008415,0.0,0.002805,29,6.3,0,...,50,200,6,3,71,107,106,215,0,3
7,122,0.000000,0.0,0.000000,0.000000,0.0,0.000000,83,0.5,6,...,62,130,0,0,122,122,123,3,1,3
8,122,0.000000,0.0,0.001517,0.000000,0.0,0.000000,84,0.5,5,...,62,130,0,0,122,122,123,3,1,3
9,122,0.000000,0.0,0.002967,0.000000,0.0,0.000000,86,0.3,6,...,62,130,1,0,122,122,123,1,1,3

### Cardiotocographic Dataset Features

The columns in this dataset represent measurements and variables
associated with cardiotocographic observations.

## Excel (XLSX) Datasets

In [7]:
excel1_df = pd.read_excel("data/dataset1.xlsx")

excel1_df.head(10)

   OrderDate UserId  ProductId  PinCode  Revenue  Units  Cancelled_Units
0 2017-11-01  User1          2   560095    999.0      1                1
1 2017-11-01  User2          3   560076    539.0      1                0
2 2017-11-01  User2          4   560076    499.0      1                0
3 2017-11-01  User2          5   560076   1012.0      1                0
4 2017-11-01  User3          6   700107    849.0      1                0
5 2017-11-01  User4          7   560067    539.0      1                0
6 2017-11-01  User5         10   122001    949.0      1                0
7 2017-11-01  User6         12   110030    484.0      1                0
8 2017-11-01  User7         19   110092    949.0      1                0
9 2017-11-01  User8         20   500059    451.0      1                0

#### Excel Dataset 1 Features

- **OrderDate** – The date when the customer order was placed.
- **UserId** – A unique identifier for the user or customer who placed the order.
- **ProductId** – A unique identifier for the product that was ordered.
- **PinCode** – The postal or ZIP code associated with the order or customer location.
- **Revenue** – The amount of revenue generated from the order.
- **Units** – The number of product units ordered.
- **Cancelled_Units** – The number of units from the order that were cancelled.

In [8]:
excel2_df = pd.read_excel("data/dataset2.xlsx")

excel2_df.head(10)

                Name    Transaction_date   Product  Price Payment_Type
0           carolina 2009-01-02 06:17:00  Product1   1200   Mastercard
1             Betina 2009-01-02 04:53:00  Product1   1200         Visa
2  Federica e Andrea 2009-01-02 13:08:00  Product1   1200   Mastercard
3              Gouya 2009-01-03 14:44:00  Product1   1200         Visa
4            Gerd W  2009-01-04 12:56:00  Product2   3600         Visa
5           LAURENCE 2009-01-04 13:19:00  Product1   1200         Visa
6              Fleur 2009-01-04 20:11:00  Product1   1200   Mastercard
7               adam 2009-01-02 20:09:00  Product1   1200   Mastercard
8    Renee Elisabeth 2009-01-04 13:17:00  Product1   1200   Mastercard
9              Aidan 2009-01-04 14:11:00  Product1   1200         Visa

#### Excel Dataset 2 Features

- **Name** – The name of the customer who made the transaction.
- **Transaction_date** – The date and time when the transaction occurred.
- **Product** – The product that was purchased in the transaction.
- **Price** – The price or amount associated with the purchased product.
- **Payment_Type** – The method of payment used for the transaction, such as Visa or Mastercard.

In [9]:
excel3_df = pd.read_excel("data/dataset3.xlsx")

excel3_df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
6,30570,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092,Toby Swindell,Consumer,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical
7,31192,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High
8,40099,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,FUR-BO-5957,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2,0.0,54.7136,25.27,High
9,36258,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,FUR-CH-4421,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,11.13,High

#### Excel Dataset 3 Features

- **Row ID** – A unique number assigned to each row or transaction record.
- **Order ID** – A unique identifier assigned to each customer order.
- **Order Date** – The date when the customer placed the order.
- **Ship Date** – The date when the order was shipped.
- **Ship Mode** – The shipping method used for the order, such as First Class, Second Class, Standard Class, or Same Day.
- **Customer ID** – A unique identifier assigned to each customer.
- **Customer Name** – The name of the customer who placed the order.
- **Segment** – The customer category, such as Consumer, Corporate, or Home Office.
- **Postal Code** – The postal or ZIP code associated with the customer's location.
- **City** – The city associated with the order.
- **State** – The state or administrative area associated with the order.
- **Country** – The country where the order was placed or delivered.
- **Region** – The geographic region associated with the order.
- **Market** – The broader geographic market associated with the order.
- **Product ID** – A unique identifier assigned to the product.
- **Category** – The main category of the product, such as Technology or Furniture.
- **Sub-Category** – A more specific classification of the product, such as Phones, Chairs, or Copiers.
- **Product Name** – The full name or description of the product purchased.
- **Sales** – The total sales amount generated by the transaction.
- **Quantity** – The number of units purchased in the transaction.
- **Discount** – The discount applied to the transaction.
- **Profit** – The amount of profit earned from the transaction.
- **Shipping Cost** – The cost associated with shipping the order.
- **Order Priority** – The priority level assigned to the order, such as Critical, High, or Medium.

# JSON Datasets

In [34]:
json1_df = pd.read_json("data/Shop.json")

json1_df.head(10)

   ShopId                                           products
0     431  [{'productId': '1234', 'productName': 'non veg...
1     432  [{'productId': '7234', 'productName': 'non veg...
2     433  [{'productId': '1214', 'productName': 'non veg...
3     434  [{'productId': '1334', 'productName': 'non veg...
4     435  [{'productId': '7734', 'productName': 'non veg...
5     436  [{'productId': '1231', 'productName': 'non veg...

#### Shop JSON Dataset Features

- **ShopId** – A unique identifier assigned to each shop.
- **products** – Contains information about the products associated with each shop, such as product ID, product name, and other product details.

In [32]:
json2_df = pd.read_json("data/products.json")

json2_df.head(10)

,id,name,description,price
0,1,Water - San Pellegrino,curae nulla dapibus dolor vel est donec odio j...,80
1,2,Cape Capensis - Fillet,rutrum neque aenean auctor gravida sem praesen...,53
2,3,Bread - Bistro Sour,ac est lacinia nisi venenatis tristique fusce ...,22
3,4,Lamb - Shoulder,quam sapien varius ut blandit non interdum in ...,16
4,5,Lettuce - Arugula,vel nisl duis ac nibh fusce lacus purus alique...,11
5,6,Kahlua,porttitor lorem id ligula suspendisse ornare c...,82
6,7,"Doilies - 5, Paper",ut massa volutpat convallis morbi odio odio el...,3
7,8,Crackers - Graham,at velit eu est congue elementum in hac habita...,28
8,9,Long Island Ice Tea,quam a odio in hac habitasse platea dictumst m...,69
9,10,Pork - Kidney,ullamcorper purus sit amet nulla quisque arcu ...,78

### Products JSON Dataset Features

- **id:** A unique numerical identifier assigned to each product.
- **name:** The name of the product.
- **description:** A brief description of the product.
- **price:** The numerical price associated with the product.

In [33]:
json3_df = pd.read_json("data/people.json", lines=True)

json3_df.head(10)

      id     name   age    city    address
0  123.0     Andy  30.0     NaN        NaN
1  124.0   Justin  19.0  berlin  street 23
2    NaN  Justina   NaN  berlin         23

#### People JSON Dataset Features

- **id** – A unique identifier assigned to each person.
- **name** – The name of the person.
- **age** – The age of the person.
- **city** – The city where the person lives.
- **address** – The person's street address.